// Dalga - spektrum kartları
// Her kart: [sol uç, sağ uç]
const CARDS = [
  ["Soğuk", "Sıcak"],
  ["Sessiz yer", "Gürültülü yer"],
  ["Kötü", "İyi"],
  ["Ucuz", "Pahalı"],
  ["Küçük", "Büyük"],
  ["Yavaş", "Hızlı"],
  ["Sıkıcı", "Eğlenceli"],
  ["Bilinmeyen", "Ünlü"],
  ["Sağlıksız", "Sağlıklı"],
  ["Zor", "Kolay"],
  ["Geçici moda", "Klasik"],
  ["Yasal", "Yasa dışı"],
  ["Ağır", "Hafif"],
  ["Çirkin", "Güzel"],
  ["Yuvarlak", "Köşeli"],
  ["Yalnız yapılır", "Kalabalıkla yapılır"],
  ["Gereksiz", "Gerekli"],
  ["Sıradan", "Tuhaf"],
  ["Kadınsı", "Erkeksi"],
  ["Çocuk işi", "Yetişkin işi"],
  ["Masum", "Suçlu"],
  ["Yumuşak", "Sert"],
  ["Az bilinen", "Herkesin bildiği"],
  ["Kısa ömürlü", "Uzun ömürlü"],
  ["Kirli", "Temiz"],
  ["Yapay", "Doğal"],
  ["Basit", "Karmaşık"],
  ["Tatlı", "Tuzlu"],
  ["Kutsal", "Bayağı"],
  ["Utanç verici", "Gurur verici"],
  ["Şanssız", "Şanslı"],
  ["Sabah insanı", "Gece insanı"],
  ["Fakir işi", "Zengin işi"],
  ["Abur cubur", "Sağlıklı atıştırmalık"],
  ["İçe dönük", "Dışa dönük"],
  ["Az pişmiş", "Çok pişmiş"],
  ["Fısıldanır", "Bağırılır"],
  ["Hafife alınır", "Ciddiye alınır"],
  ["Modası geçmiş", "Çağdaş"],
  ["Sıcak ülke", "Soğuk ülke"],
  ["Küçük şehir", "Büyük şehir"],
  ["Kısa film", "Uzun film"],
  ["Affedilir", "Affedilmez"],
  ["Sıradan yetenek", "İnanılmaz yetenek"],
  ["Faydalı uygulama", "Zaman katili uygulama"],
  ["Kötü koku", "Güzel koku"],
  ["Rahat kıyafet", "Şık kıyafet"],
  ["Ev işi", "Ofis işi"],
  ["Güvenli", "Tehlikeli"],
  ["Abartılan", "Hakkı yenen"],
  ["Unutulur", "Akılda kalır"],
  ["Kırılgan", "Sağlam"],
  ["Sıvı", "Katı"],
  ["Yenmez", "Yenilebilir"],
  ["Genç işi", "Yaşlı işi"],
  ["Kaba", "Kibar"],
  ["Sakin film", "Aksiyon filmi"],
  ["Çabuk bozulur", "Uzun süre dayanır"],
  ["İşe yaramaz hediye", "Harika hediye"],
  ["Az kalorili", "Çok kalorili"],
  ["Sıradan meslek", "Havalı meslek"],
  ["Bencilce", "Fedakârca"],
  ["Şehir hayatı", "Köy hayatı"],
  ["Geçmiş", "Gelecek"],
  ["Öğrenilir", "Doğuştan gelir"],
  ["Yavaş yenir", "Hızlı yenir"],
  ["Karanlık", "Aydınlık"],
  ["Uzak tanıdık", "Sıkı arkadaş"],
  ["Küçük yalan", "Büyük yalan"],
  ["Kolay iş", "Zahmetli iş"],
  ["Sıradan gün", "Özel gün"],
  ["Az baharatlı", "Çok baharatlı"],
  ["Ciddi meslek", "Eğlenceli meslek"],
  ["Gerçekçi", "Fantastik"],
  ["Kişisel", "Herkese açık"],
  ["Zararsız hayvan", "Tehlikeli hayvan"],
  ["Kolay telaffuz", "Zor telaffuz"],
  ["Kötü şarkı", "İyi şarkı"],
  ["Sıcak içecek", "Soğuk içecek"],
  ["Kısa tatil", "Uzun tatil"],
  ["Sıradan isim", "Sıra dışı isim"],
  ["Bilim", "Sanat"],
  ["Basit rahatsızlık", "Ciddi hastalık"],
  ["Gereksiz eşya", "Olmazsa olmaz eşya"],
  ["Az kişi sever", "Herkes sever"],
  ["Şakası yapılabilir", "Şakası yapılamaz"],
  ["Kolay unutulur", "Travmatik"],
  ["Sıradan yemek", "Lüks yemek"],
  ["Yerli", "Yabancı"],
  ["Kolay kanar", "Kuşkucu"],
  ["Mantıklı korku", "Mantıksız korku"],
  ["Yavaş şarkı", "Hızlı şarkı"],
  ["Az efor", "Çok efor"],
  ["Kötü alışkanlık", "İyi alışkanlık"],
  ["Sıkıcı ders", "Eğlenceli ders"],
  ["Küçük hata", "Büyük hata"],
  ["Utangaç", "Cesur"],
  ["Sade", "Gösterişli"],
  ["Ekonomik", "Savurgan"],
  ["Erkenci", "Geç kalan"],
  ["Sağlıklı ilişki", "Zehirli ilişki"],
  ["Hafif ceza", "Ağır ceza"],
  ["Çirkin bina", "Güzel bina"],
  ["Gizli tutulur", "Herkese anlatılır"],
  ["Amatör", "Profesyonel"],
  ["Sıradan süper güç", "Efsane süper güç"],
  ["Rahatlatıcı ses", "Sinir bozucu ses"],
  ["Kolay hobi", "Zor hobi"],
  ["Evcil", "Vahşi"],
  ["Az izlenen", "Çok izlenen"],
  ["Ahlaklı", "Ahlaksız"],
  ["Küçük suç", "Büyük suç"],
  ["Katlanılabilir", "Dayanılmaz"],
  ["Şansa bağlı", "Yeteneğe bağlı"],
  ["Anlamsız", "Derin"],
  ["Komik", "Trajik"],
  ["Kolay pişer", "Zor pişer"],
  ["Sıradan hayvan", "Egzotik hayvan"],
  ["Havalı", "Zavallı"],
  ["Nostaljik", "Fütüristik"],
  ["Sıkıcı şehir", "Heyecanlı şehir"],
  ["Kısa vadeli haz", "Uzun vadeli fayda"],
  ["Masum yalan", "Kötü niyetli yalan"],
  ["Berbat film", "Başyapıt"],
  ["Kolay ilişki", "Zor ilişki"],
  ["Yalnızlık", "Kalabalık"],
  ["Alçakgönüllü", "Kibirli"],
  ["Az yer kaplar", "Çok yer kaplar"],
  ["Sıradan koku", "Unutulmaz koku"],
  ["Çirkin isim", "Güzel isim"],
  ["Yaz aktivitesi", "Kış aktivitesi"],
  ["Kolay saklanır", "Zor saklanır"],
  ["Yararsız bilgi", "Hayat kurtaran bilgi"],
  ["Sessiz sinema", "Karaoke"],
  ["Gündelik dert", "Büyük dert"],
  ["Sıkıcı hediye", "Sürprizli hediye"],
  ["Tembel", "Çalışkan"],
  ["Doğaçlama", "Planlı"],
  ["Kısa mesaj", "Uzun mesaj"],
  ["Ucuz tatil", "Lüks tatil"],
  ["İhtiyaç", "Lüks"],
  ["Sıradan tişört", "Abartılı tişört"],
  ["Yorucu spor", "Dinlendirici spor"],

  // --- Fiziksel / somut ---
  ["Yaygın", "Nadir"],
  ["Eski", "Yeni"],

  // --- Yeme içme ---
  ["Kötü kahvaltı", "Mükemmel kahvaltı"],
  ["Atıştırmalık", "Tam öğün"],
  ["Acısız", "Çok acı"],
  ["Bayat", "Taze"],
  ["Açık çay", "Koyu çay"],
  ["Yanına ayran yakışmaz", "Ayransız olmaz"],
  ["Kahvaltıda yenmez", "Kahvaltının olmazsa olmazı"],
  ["Çocuk yemeği", "Yetişkin yemeği"],
  ["Ucuz lokanta", "Pahalı restoran"],
  ["Soğuk yenir", "Sıcak yenir"],
  ["Tarifi kolay", "Tarifi zor"],

  // --- Kişilik ve davranış ---
  ["Cimri", "Cömert"],
  ["Ciddi", "Şakacı"],
  ["Dağınık", "Titiz"],
  ["Mantıklı", "Duygusal"],
  ["Takıntılı", "Umursamaz"],
  ["Güvenilmez", "Güvenilir"],
  ["Uyumlu", "İnatçı"],

  // --- Ahlak ve toplum ---
  ["Kabul edilebilir", "Kabul edilemez"],
  ["Özür gerektirmez", "Özür şart"],
  ["Görgüsüzlük", "İncelik"],
  ["Bahşiş verilmez", "Mutlaka bahşiş verilir"],
  ["Yalan sayılmaz", "Düpedüz yalan"],

  // --- Duygu ve deneyim ---
  ["Rahatlatıcı", "Stresli"],
  ["Utanç verici", "Havalı"],
  ["Acıklı", "Komik"],
  ["Yorucu", "Dinlendirici"],
  ["Hayal kırıklığı", "Beklenenden iyi"],
  ["Korkutucu değil", "Dehşet verici"],
  ["Sinir bozucu", "Keyifli"],
  ["Zorunluluk", "Zevk"],

  // --- Popüler kültür ---
  ["Unutulmuş", "Kült"],
  ["Kötü kötü adam", "Efsane kötü adam"],
  ["Bir kere izlenir", "Defalarca izlenir"],
  ["Reklamı iyi", "Ürünü iyi"],
  ["Sanat değil", "Yüksek sanat"],
  ["Bilim değil", "Kesin bilim"],

  // --- Türkiye'ye özel ---
  ["Sakin semt", "Curcunalı semt"],
  ["Kısa yol", "Trafiği kötü yol"],
  ["Kimse gitmez", "Turist dolu tatil yeri"],
  ["Kaçırılabilir bayram ziyareti", "Kaçırılmaz bayram ziyareti"],
  ["Uygunsuz düğün hediyesi", "Mükemmel düğün hediyesi"],
  ["Yazlık şehir", "Kışlık şehir"],
  ["Kışın giyilmez", "Kışın şart"],
  ["Küçük şehir işi", "Büyük şehir işi"],
  ["Kirası ucuz", "Kirası fahiş"],
  ["Anlaşılmaz argo", "Herkesin bildiği argo"],

  // --- Nesneler ve teknoloji ---
  ["Kolay tamir edilir", "Tamiri imkânsız"],
  ["Çirkin tasarım", "Güzel tasarım"],
  ["Kullanışsız", "Çok kullanışlı"],
  ["Modası geçmiş teknoloji", "Geleceğin teknolojisi"],
  ["Kimse okumaz", "Herkes okur"],
  ["Kimse kullanmaz", "Herkes kullanır"],

  // --- Hayvanlar ve doğa ---
  ["Çirkin hayvan", "Sevimli hayvan"],
  ["Evde beslenmez", "Evde beslenir"],
  ["Aptal hayvan", "Zeki hayvan"],
  ["Görülmesi kolay", "Görülmesi zor"],
  ["Sıradan manzara", "Nefes kesici manzara"],

  // --- Yetenek ve zorluk ---
  ["Öğrenmesi kolay", "Öğrenmesi zor"],
  ["Herkes yapabilir", "Çok az kişi yapabilir"],
  ["Fiziksel güç ister", "Zekâ ister"],
  ["Spor sayılmaz", "Gerçek spor"],

  // --- Zaman ve yaşam ---
  ["Sabah aktivitesi", "Gece aktivitesi"],
  ["Hafta içi", "Hafta sonu"],
  ["Anlık karar", "Yıllarca düşünülür"],
  ["Ertelenebilir", "Acil"],

  // --- Soyut / tartışma çıkaranlar ---
  ["Şans", "Kader"],
  ["Gelenek", "Batıl inanç"],
  ["Hobi", "Bağımlılık"],
  ["Tavsiye", "Emir"],
  ["İltifat", "Hakaret"],
  ["Arkadaşlık", "Aşk"],
  ["Yardım", "Acıma"],
];
